.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayMemAlloc - Debug ]----------"
	@cd "ArrayMemAlloc" && "$(MAKE)" -f  "ArrayMemAlloc.mk"
clean:
	@echo "----------Cleaning project:[ ArrayMemAlloc - Debug ]----------"
	@cd "ArrayMemAlloc" && "$(MAKE)" -f  "ArrayMemAlloc.mk" clean
